import { formatLKR, type ClientInvoice } from '@/data/appState';

const dateText = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const escapeHtml = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const numberToWords = (value: number) => `Sri Lankan Rupees ${integerToWords(Math.floor(value))}${Math.round((value - Math.floor(value)) * 100) ? ` and ${integerToWords(Math.round((value - Math.floor(value)) * 100))} Cents` : ''} Only`;
function integerToWords(value: number): string { const ones = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen']; const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety']; if (value < 20) return ones[value]; if (value < 100) return `${tens[Math.floor(value / 10)]}${value % 10 ? ` ${ones[value % 10]}` : ''}`; if (value < 1000) return `${ones[Math.floor(value / 100)]} Hundred${value % 100 ? ` ${integerToWords(value % 100)}` : ''}`; if (value < 1000000) return `${integerToWords(Math.floor(value / 1000))} Thousand${value % 1000 ? ` ${integerToWords(value % 1000)}` : ''}`; if (value < 1000000000) return `${integerToWords(Math.floor(value / 1000000))} Million${value % 1000000 ? ` ${integerToWords(value % 1000000)}` : ''}`; return `${integerToWords(Math.floor(value / 1000000000))} Billion`; }

export function renderTaxInvoiceHtml(invoice: ClientInvoice, autoPrint = true): string {
  const company = invoice.companyInfo ?? { name: 'Harith Engineering & Company (Pvt) Ltd', tin: '', vatNumber: '', ssclNumber: '', stampDRN: '', address: '', telephone: '' };
  const client = invoice.clientInfo ?? { name: invoice.clientName, tin: '', vatNumber: '', address: '', phone: '' };
  const lines = invoice.lineItems ?? [];
  const companyTax = [company.tin && `TIN: ${company.tin}`, company.vatNumber && `VAT No: ${company.vatNumber}`, company.ssclNumber && `SSCL No.: ${company.ssclNumber}`, company.stampDRN && `Stamp D.R.N: ${company.stampDRN}`].filter(Boolean).map((value) => `<div>${escapeHtml(value as string)}</div>`).join('');
  const clientVat = client.vatNumber ? `<div>VAT No: ${escapeHtml(client.vatNumber)}</div>` : '';
  const rows = lines.map((line) => `<tr><td>${escapeHtml(line.reference)}</td><td>${escapeHtml(line.material)}</td><td>${line.quantity.toFixed(2)}</td><td>${formatLKR(line.unitPrice)}</td><td>${formatLKR(line.amount)}</td></tr>`).join('');
  const additional = invoice.additionalInformation?.trim() ? `<div class="box extra"><h3>Additional Key Information</h3><div>${escapeHtml(invoice.additionalInformation).replace(/\n/g, '<br />')}</div></div>` : '';
  const totalAfterSscl = invoice.subtotal + (invoice.ssclEnabled ? invoice.sscl : 0);
  const printScript = autoPrint ? '<script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script>' : '';
  return `<html><head><title>Tax Invoice ${escapeHtml(invoice.id)}</title><style>body{font-family:Arial;color:#172033;padding:32px}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #dbe3ef;padding:9px;text-align:left}th{background:#eff6ff}.boxes{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.box{border:1px solid #dbe3ef;border-radius:8px;padding:16px}.box h3{margin:0 0 8px}.extra{margin-top:16px}.totals{margin:24px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:7px}.grand{border-top:2px solid #172033;font-weight:bold}.signature{margin-top:24px;border:1px solid #dbe3ef;border-radius:8px;padding:24px;text-align:center}</style></head><body><h1>Tax Invoice</h1><p><strong>Invoice Number:</strong> ${escapeHtml(invoice.id)}</p><p><strong>Date of Invoice:</strong> ${dateText(invoice.invoiceDate)}</p><div class="boxes"><div class="box"><h3>Company Information</h3><div>${escapeHtml(company.name)}</div>${companyTax}<div>${escapeHtml(company.address || '—')}</div><div>Telephone: ${escapeHtml(company.telephone || '—')}</div></div><div class="box"><h3>Client Information</h3><div>${escapeHtml(client.name)}</div><div>TIN: ${escapeHtml(client.tin || '—')}</div>${clientVat}<div>${escapeHtml(client.address || '—')}</div><div>Telephone: ${escapeHtml(client.phone || '—')}</div></div></div>${additional}<p><strong>Site:</strong> ${escapeHtml(invoice.site || 'All sites')}</p><table><thead><tr><th>Reference</th><th>Description</th><th>QTY (Ton)</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${rows || '<tr><td colspan="5">No stored line items.</td></tr>'}</tbody></table><div class="totals"><div><span>Subtotal</span><strong>${formatLKR(invoice.subtotal)}</strong></div>${invoice.ssclEnabled ? `<div><span>SSCL (${invoice.ssclPercent ?? 'stored rate'}%)</span><strong>${formatLKR(invoice.sscl)}</strong></div>` : ''}<div><span>Total After SSCL</span><strong>${formatLKR(totalAfterSscl)}</strong></div>${invoice.vatEnabled ? `<div><span>VAT (${invoice.vatPercent ?? 'stored rate'}%)</span><strong>${formatLKR(invoice.vat)}</strong></div>` : ''}<div class="grand"><span>Total Amount</span><strong>${formatLKR(invoice.totalAmount)}</strong></div></div><table><tbody><tr><th>Total Amount in Words</th><td>${numberToWords(invoice.totalAmount)}</td></tr><tr><th>Mode of Payment</th><td>${escapeHtml(invoice.paymentMode || '—')}</td></tr></tbody></table><div class="signature"><strong>${escapeHtml(company.name)}</strong><div>......................................................................</div><strong>Harith Gamage</strong><div><strong>(Director)</strong></div></div>${printScript}</body></html>`;
}
