import { formatLKR, type PerformaInvoice } from '@/data/appState';

const dateText = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const escapeHtml = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function renderPerformaInvoiceHtml(invoice: PerformaInvoice, autoPrint = true): string {
  const company = invoice.companyInfo;
  const client = invoice.clientInfo;
  const rows = invoice.lineItems.map((line, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(line.material)}</td><td>${escapeHtml(line.unit ?? 'Ton')}</td><td>${line.quantity.toFixed(2)}</td><td>${formatLKR(line.unitPrice)}</td><td>${formatLKR(line.amount)}</td></tr>`).join('');
  const project = invoice.additionalInformation?.trim() ? `<p><strong>Project Name:</strong> ${escapeHtml(invoice.additionalInformation)}</p>` : '';
  const totalAfterSscl = invoice.subtotal + (invoice.ssclEnabled ? invoice.sscl : 0);
  const printScript = autoPrint ? '<script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script>' : '';
  return `<html><head><title>Performa Invoice ${escapeHtml(invoice.id)}</title><style>body{font-family:Arial;color:#172033;padding:32px}header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}.brand{font-size:24px;font-weight:bold}.info{border:1px solid #dbe3ef;padding:14px;min-width:270px}.client{border:1px solid #dbe3ef;padding:14px;margin-top:18px;width:48%}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #dbe3ef;padding:9px;text-align:left}th{background:#eff6ff}.totals{margin:24px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:7px}.grand{border-top:2px solid #172033;font-weight:bold}.signature{margin-top:30px;border:1px solid #dbe3ef;padding:24px;text-align:center}</style></head><body><header><div><div class="brand">Performa Invoice</div><div class="client"><strong>Client Company</strong><div>${escapeHtml(client?.name ?? invoice.clientName)}</div><div>${escapeHtml(client?.address ?? '—')}</div><div>Client VAT No.: ${escapeHtml(client?.vatNumber ?? '—')}</div></div></div><div class="info"><div><strong>Date:</strong> ${dateText(invoice.invoiceDate)}</div><div><strong>Invoice Number:</strong> ${escapeHtml(invoice.id)}</div><div><strong>VAT No:</strong> ${escapeHtml(company.vatNumber || '—')}</div><div><strong>Stamp D.R.N:</strong> ${escapeHtml(company.stampDRN || '—')}</div><div><strong>SSCL Number:</strong> ${escapeHtml(company.ssclNumber || '—')}</div></div></header>${project}<p><strong>Site:</strong> ${escapeHtml(invoice.site || '—')}</p><table><thead><tr><th>No</th><th>Description</th><th>Unit</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Subtotal</span><strong>${formatLKR(invoice.subtotal)}</strong></div>${invoice.ssclEnabled ? `<div><span>SSCL (${invoice.ssclPercent}%)</span><strong>${formatLKR(invoice.sscl)}</strong></div>` : ''}<div><span>Total After SSCL</span><strong>${formatLKR(totalAfterSscl)}</strong></div>${invoice.vatEnabled ? `<div><span>VAT (${invoice.vatPercent}%)</span><strong>${formatLKR(invoice.vat)}</strong></div>` : ''}<div class="grand"><span>Total Amount</span><strong>${formatLKR(invoice.totalAmount)}</strong></div></div><div class="signature"><strong>Harith Engineering &amp; Company (Pvt) Ltd</strong><div>............................................................................</div><strong>Harith Gamage</strong><div><strong>Director</strong></div></div>${printScript}</body></html>`;
}
