import { useMemo, useState } from 'react';
import { useApp, formatLKR, type ClientInvoice } from '@/data/appState';
import { Card, CardHeader, Badge } from '@/components/ui';
import { Pagination } from '@/components/Pagination';

const PAGE_SIZE = 10;
const dateText = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

export function PrintedInvoicesTab() {
  const { clientInvoices, updateClientInvoice } = useApp();
  const [filters, setFilters] = useState({ client: '', site: '', from: '', to: '', status: '' });
  const [page, setPage] = useState(1);
  const sites = [...new Set(clientInvoices.filter((invoice) => !filters.client || invoice.clientId === filters.client).map((invoice) => invoice.site))];
  const filtered = useMemo(() => clientInvoices.filter((invoice) => (!filters.client || invoice.clientId === filters.client) && (!filters.site || invoice.site === filters.site) && (!filters.from || invoice.invoiceDate >= filters.from) && (!filters.to || invoice.invoiceDate <= filters.to) && (!filters.status || invoice.paymentStatus === filters.status)), [clientInvoices, filters]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const updateFilter = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const clear = () => { setFilters({ client: '', site: '', from: '', to: '', status: '' }); setPage(1); };
  return <Card className="animate-fade-up"><CardHeader title="Printed Invoices" action={<Badge tone="brand">{filtered.length} invoices</Badge>} /><div className="grid grid-cols-1 gap-3 border-b border-slate-100 p-5 md:grid-cols-2 lg:grid-cols-[1.2fr_1.2fr_1fr_1fr_1fr_auto] lg:items-end"><Field label="Client"><select value={filters.client} onChange={(event) => updateFilter('client', event.target.value)} className="form-select"><option value="">All clients</option>{[...new Map(clientInvoices.map((invoice) => [invoice.clientId, invoice.clientName]))].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field><Field label="Site"><select value={filters.site} onChange={(event) => updateFilter('site', event.target.value)} className="form-select"><option value="">All sites</option>{sites.map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="From Date"><input type="date" value={filters.from} onChange={(event) => updateFilter('from', event.target.value)} className="form-input" /></Field><Field label="To Date"><input type="date" value={filters.to} onChange={(event) => updateFilter('to', event.target.value)} className="form-input" /></Field><Field label="Payment Status"><select value={filters.status} onChange={(event) => updateFilter('status', event.target.value)} className="form-select"><option value="">All statuses</option><option value="Received">Received</option><option value="Pending">Pending</option></select></Field><button type="button" onClick={clear} className="min-h-10 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-600">Clear Filters</button></div><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-400"><th className="px-4 py-3 font-semibold">Invoice Number</th><th className="px-4 py-3 font-semibold">Client Name</th><th className="px-4 py-3 font-semibold">Site</th><th className="px-4 py-3 font-semibold">Invoice Date</th><th className="px-4 py-3 font-semibold">Date Duration</th><th className="px-4 py-3 text-right font-semibold">Subtotal</th><th className="px-4 py-3 text-right font-semibold">SSCL</th><th className="px-4 py-3 text-right font-semibold">VAT</th><th className="px-4 py-3 text-right font-semibold">Total Amount</th><th className="px-4 py-3 font-semibold">Payment Status</th><th className="px-4 py-3 text-center font-semibold">Action</th></tr></thead><tbody className="divide-y divide-slate-50">{visible.map((invoice) => <InvoiceRow key={invoice.id} invoice={invoice} onStatusChange={updateClientInvoice} />)}</tbody></table>{visible.length === 0 && <div className="px-5 py-12 text-center text-sm text-slate-400">No printed invoices match the selected filters.</div>}</div><Pagination page={page} pageCount={pageCount} total={filtered.length} pageSize={PAGE_SIZE} onPageChange={setPage} /></Card>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function InvoiceRow({ invoice, onStatusChange }: { invoice: ClientInvoice; onStatusChange: (id: string, patch: Partial<ClientInvoice>) => void }) { return <tr className="transition hover:bg-slate-50/60"><td className="px-4 py-3 font-semibold text-slate-700">{invoice.id}</td><td className="px-4 py-3">{invoice.clientName}</td><td className="px-4 py-3">{invoice.site}</td><td className="px-4 py-3">{dateText(invoice.invoiceDate)}</td><td className="px-4 py-3">{dateText(invoice.fromDate)} to {dateText(invoice.toDate)}</td><td className="px-4 py-3 text-right">{formatLKR(invoice.subtotal)}</td><td className="px-4 py-3 text-right">{formatLKR(invoice.sscl)}</td><td className="px-4 py-3 text-right">{formatLKR(invoice.vat)}</td><td className="px-4 py-3 text-right font-bold text-brand-700">{formatLKR(invoice.totalAmount)}</td><td className="px-4 py-3"><Badge tone={invoice.paymentStatus === 'Received' ? 'success' : 'amber'}>{invoice.paymentStatus}</Badge></td><td className="px-4 py-3 text-center"><button type="button" onClick={() => onStatusChange(invoice.id, { paymentStatus: invoice.paymentStatus === 'Received' ? 'Pending' : 'Received' })} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{invoice.paymentStatus === 'Received' ? 'Mark Pending' : 'Mark Received'}</button></td></tr>; }