import { useMemo, useState } from 'react';
import { useApp, formatLKR, type SupplierVoucher } from '@/data/appState';
import { Card, CardHeader, Badge } from '@/components/ui';
import { Pagination } from '@/components/Pagination';

const PAGE_SIZE = 10;
const dateText = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

export function PrintedVouchersTab() {
  const { supplierVouchers, updateSupplierVoucher } = useApp();
  const [filters, setFilters] = useState({ supplier: '', from: '', to: '', status: '' });
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => supplierVouchers.filter((voucher) => (!filters.supplier || voucher.supplierId === filters.supplier) && (!filters.from || voucher.voucherDate >= filters.from) && (!filters.to || voucher.voucherDate <= filters.to) && (!filters.status || voucher.paymentStatus === filters.status)), [filters, supplierVouchers]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const updateFilter = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const clear = () => { setFilters({ supplier: '', from: '', to: '', status: '' }); setPage(1); };
  return <Card className="animate-fade-up"><CardHeader title="Printed Vouchers" action={<Badge tone="brand">{filtered.length} vouchers</Badge>} /><div className="grid grid-cols-1 gap-3 border-b border-slate-100 p-5 md:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1fr_auto] lg:items-end"><Field label="Supplier Name"><select value={filters.supplier} onChange={(event) => updateFilter('supplier', event.target.value)} className="form-select"><option value="">All suppliers</option>{[...new Map(supplierVouchers.map((voucher) => [voucher.supplierId, voucher.supplierName]))].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field><Field label="From Date"><input type="date" value={filters.from} onChange={(event) => updateFilter('from', event.target.value)} className="form-input" /></Field><Field label="To Date"><input type="date" value={filters.to} onChange={(event) => updateFilter('to', event.target.value)} className="form-input" /></Field><Field label="Payment Status"><select value={filters.status} onChange={(event) => updateFilter('status', event.target.value)} className="form-select"><option value="">All statuses</option><option value="Paid">Paid</option><option value="Unpaid">Unpaid</option></select></Field><button type="button" onClick={clear} className="min-h-10 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-600">Clear Filters</button></div><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-400"><th className="px-4 py-3 font-semibold">Voucher Number</th><th className="px-4 py-3 font-semibold">Supplier Name</th><th className="px-4 py-3 font-semibold">Voucher Date</th><th className="px-4 py-3 font-semibold">Date Duration</th><th className="px-4 py-3 text-right font-semibold">Subtotal</th><th className="px-4 py-3 text-right font-semibold">SSCL</th><th className="px-4 py-3 text-right font-semibold">VAT</th><th className="px-4 py-3 text-right font-semibold">Grand Total</th><th className="px-4 py-3 font-semibold">Payment Status</th><th className="px-4 py-3 text-center font-semibold">Action</th></tr></thead><tbody className="divide-y divide-slate-50">{visible.map((voucher) => <VoucherRow key={voucher.id} voucher={voucher} onStatusChange={updateSupplierVoucher} />)}</tbody></table>{visible.length === 0 && <div className="px-5 py-12 text-center text-sm text-slate-400">No printed vouchers match the selected filters.</div>}</div><Pagination page={page} pageCount={pageCount} total={filtered.length} pageSize={PAGE_SIZE} onPageChange={setPage} /></Card>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function VoucherRow({ voucher, onStatusChange }: { voucher: SupplierVoucher; onStatusChange: (id: string, patch: Partial<SupplierVoucher>) => void }) { return <tr className="transition hover:bg-slate-50/60"><td className="px-4 py-3 font-semibold text-slate-700">{voucher.id}</td><td className="px-4 py-3">{voucher.supplierName}</td><td className="px-4 py-3">{dateText(voucher.voucherDate)}</td><td className="px-4 py-3">{dateText(voucher.fromDate)} to {dateText(voucher.toDate)}</td><td className="px-4 py-3 text-right">{formatLKR(voucher.subtotal)}</td><td className="px-4 py-3 text-right">{formatLKR(voucher.sscl)}</td><td className="px-4 py-3 text-right">{formatLKR(voucher.vat)}</td><td className="px-4 py-3 text-right font-bold text-brand-700">{formatLKR(voucher.grandTotal)}</td><td className="px-4 py-3"><Badge tone={voucher.paymentStatus === 'Paid' ? 'success' : 'amber'}>{voucher.paymentStatus}</Badge></td><td className="px-4 py-3 text-center"><button type="button" onClick={() => onStatusChange(voucher.id, { paymentStatus: voucher.paymentStatus === 'Paid' ? 'Unpaid' : 'Paid' })} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{voucher.paymentStatus === 'Paid' ? 'Mark Unpaid' : 'Mark Paid'}</button></td></tr>; }