import { useState } from 'react';
import { useApp, type SystemUser } from '@/data/appState';
import { Card, CardHeader, Badge } from '@/components/ui';
import { DashboardHeader } from '@/components/Controls';
import { Icon } from '@/components/Icon';
import { showToast } from '@/components/Toast';
import { UserAvatar } from '@/components/UserAvatar';

type Role = SystemUser['role'];
const roles: Role[] = ['Port Staff', 'Office Staff', 'Admin'];
const permissions = [
  ['Dashboard', 'View', 'View', 'Full Access'], ['Port Operations', 'Edit Assigned Fields', 'View/Edit', 'Full Access'], ['Supplier PO Column', 'No Edit', 'Edit', 'Edit'],
  ['Confirm Port Operation Changes', 'As Applicable', 'Yes', 'Yes'], ['Client POs', 'No', 'View/Edit', 'Full Access'], ['Supplier POs', 'No', 'View/Edit', 'Full Access'],
  ['Completed Entries', 'As Assigned', 'View/Edit', 'Full Access'], ['Invoices', 'No', 'View/Create', 'Full Access'], ['Printed Invoices', 'No', 'View/Manage', 'Full Access'],
  ['Supplier Vouchers', 'No', 'View/Create', 'Full Access'], ['Printed Vouchers', 'No', 'View/Manage', 'Full Access'], ['General Ledger', 'No', 'View', 'Full Access'],
  ['Settings', 'No', 'Limited/No', 'Full Access'], ['Users & Access', 'No', 'No', 'Full Access'],
];
const emptyForm = { fullName: '', username: '', password: '', confirmPassword: '', role: 'Port Staff' as Role, status: 'Active' as SystemUser['status'] };

export function UsersPage() {
  const { users, addUser, updateUser } = useApp();
  const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.fullName.trim() || !form.username.trim() || !form.password || form.password !== form.confirmPassword) return; const { confirmPassword: _confirmPassword, ...user } = form; if (editingId) { updateUser(editingId, user); showToast('User updated successfully'); } else { addUser({ ...user, lastLogin: 'Never' }); showToast('User created successfully'); } setForm(emptyForm); setEditingId(null); setShowForm(false); };
  const edit = (user: SystemUser) => { setForm({ fullName: user.fullName, username: user.username, password: user.password, confirmPassword: user.password, role: user.role, status: user.status }); setEditingId(user.id); setShowForm(true); };
  return <div className="space-y-5"><DashboardHeader title="Users & Access" subtitle="Manage system users, roles and access permissions"><button type="button" onClick={() => { setForm(emptyForm); setEditingId(null); setShowForm(true); }} className="flex min-h-11 items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white"><Icon name="UserPlus" className="h-4 w-4" /> Add New User</button></DashboardHeader>{showForm && <Card className="animate-scale-in"><CardHeader title={editingId ? 'Edit User' : 'Add New User'} /><form onSubmit={submit} className="grid grid-cols-1 gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Full Name"><input required value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} className="form-input" /></Field><Field label="Email / Username"><input required value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} className="form-input" /></Field><Field label="Password"><input required type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="form-input" /></Field><Field label="Confirm Password"><input required type="password" value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} className="form-input" /></Field><Field label="Role"><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Role })} className="form-select">{roles.map((role) => <option key={role}>{role}</option>)}</select></Field><Field label="Account Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as SystemUser['status'] })} className="form-select"><option>Active</option><option>Inactive</option></select></Field><div className="flex gap-2 sm:col-span-2 lg:col-span-3"><button type="submit" className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">{editingId ? 'Save User' : 'Create User'}</button><button type="button" onClick={() => setShowForm(false)} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-100">Cancel</button></div></form></Card>}
    <Card className="animate-fade-up"><CardHeader title="System Users" action={<Badge tone="brand">{users.length} users</Badge>} /><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-400"><th className="px-5 py-3">User Name</th><th className="px-5 py-3">Email / Username</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Last Login</th><th className="px-5 py-3 text-center">Actions</th></tr></thead><tbody className="divide-y divide-slate-50">{users.map((user) => <tr key={user.id} className="transition hover:bg-slate-50/60"><td className="px-5 py-3 font-semibold text-slate-700">{user.fullName}</td><td className="px-5 py-3 text-slate-500">{user.username}</td><td className="px-5 py-3"><Badge tone={user.role === 'Admin' ? 'brand' : user.role === 'Office Staff' ? 'success' : 'amber'}>{user.role}</Badge></td><td className="px-5 py-3"><Badge tone={user.status === 'Active' ? 'success' : 'slate'}>{user.status}</Badge></td><td className="px-5 py-3 text-slate-500">{user.lastLogin}</td><td className="px-5 py-3"><div className="flex justify-center gap-1"><button type="button" onClick={() => edit(user)} title="Edit user" className="rounded-lg p-2 text-slate-400 hover:bg-brand-50 hover:text-brand-600"><Icon name="Pencil" className="h-4 w-4" /></button><button type="button" onClick={() => { updateUser(user.id, { status: user.status === 'Active' ? 'Inactive' : 'Active' }); showToast(`User ${user.status === 'Active' ? 'deactivated' : 'activated'}`); }} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">{user.status === 'Active' ? 'Deactivate' : 'Activate'}</button><button type="button" onClick={() => { updateUser(user.id, { password: 'demo123' }); showToast('Password reset to demo123'); }} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">Reset Password</button></div></td></tr>)}</tbody></table></div></Card>
    <Card className="animate-fade-up"><CardHeader title="Permission Matrix" /><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-400"><th className="px-5 py-3">Module / Function</th><th className="px-5 py-3">Port Staff</th><th className="px-5 py-3">Office Staff</th><th className="px-5 py-3">Admin</th></tr></thead><tbody className="divide-y divide-slate-50">{permissions.map(([module, port, office, admin]) => <tr key={module}><td className="px-5 py-3 font-semibold text-slate-700">{module}</td><td className="px-5 py-3 text-slate-500">{port}</td><td className="px-5 py-3 text-slate-500">{office}</td><td className="px-5 py-3 font-semibold text-brand-700">{admin}</td></tr>)}</tbody></table></div></Card>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }